# Generated by Django 5.2.16 on 2026-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='status',
            field=models.CharField(default='idle', max_length=50),
        ),
    ]
