# Generated by Django 5.2.16 on 2026-07-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_add_pdf_status_and_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='report_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='report_markdown',
            field=models.TextField(blank=True, null=True),
        ),
    ]
